### ISSUE TITLE
Chapter 3 LaTeX equation not displaying

### ISSUE THREAD

**Issue by jrwrigh** [benchmark-subsetting/adaptive-sampling-kit#3]
On the [Chapter 3 wiki](https://github.com/benchmark-subsetting/adaptive-sampling-kit/wiki/Chapter-3:-Experiment-Setup#setting-up-an-experiment) there's a part that appears to be an attempt to use LaTeX equation formating to display an equation.

Is it possible to get that fixed?

**Comment by pablooliveira** [comment]
Hi @u2berggeist thanks for bringing up this issue. Unfortunately, github pages discontinued support for mathjax; so I had to embed an image instead to fix this.
